kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.08927833676095703
    roll: -0
    pitch: 0
    yaw: 2.387900260277366e-05
  upper_arm:
    x: 0.0001784256338569523
    y: 0
    z: 0
    roll: 1.569367393550987
    pitch: 0
    yaw: 6.781629743275735e-05
  forearm:
    x: -0.4254969260891848
    y: 0
    z: 0
    roll: 0.003903047575412154
    pitch: 0.003039414479638508
    yaw: 5.668403500279954e-05
  wrist_1:
    x: -0.3918484743936296
    y: 0.001502838381210458
    z: 0.1108565564269838
    roll: 3.128036880479333
    pitch: 3.139166598351523
    yaw: 3.141549634919858
  wrist_2:
    x: 0.0001056586285909039
    y: -0.0947941174274347
    z: -0.000149658066412359
    roll: 1.572375095036349
    pitch: 0
    yaw: -6.572957172588542e-05
  wrist_3:
    x: -2.004433009240349e-05
    y: 0.08264223706805418
    z: -0.0001751403635191521
    roll: 1.56867707025571
    pitch: 3.141592653589793
    yaw: 3.141589757614473
  hash: calib_9838198715474137183